### ISSUE TITLE
Problem on Serializable Dictionary

### ISSUE THREAD

**Issue by Jiraiyah** [lordofduct/spacepuppy-unity-framework#1]
SerializableDictionary <string, List<int>> or SerializableDictionary <string, int[]> these two don't get serialized properly :/

Actually I think no nested collections would be serialized

**Comment by Jiraiyah** [comment]
if you got it fixed, can you please give a heads up here too?
http://forum.unity3d.com/threads/finally-a-serializable-dictionary-for-unity-extracted-from-system-collections-generic.335797/

thanks

**Comment by lordofduct** [comment]
Unity does not support serializing collections of collections. SerializableDictionary is a slapdash class to get quick unity serialization of dictionaries in unity.

As it's a class I built specifically for use by you in the referenced thread, I don't have future plans to upgrade compatibility to support collections of collections. If this support is desired, I outline how it can be accomplished in the referenced thread.
