### ISSUE TITLE
Rendering issue in DictionaryPropertyDrawer.cs for large number of elements

### ISSUE THREAD

**Issue by Chazzz** [lordofduct/spacepuppy-unity-framework#9]
In DictionaryPropertyDrawer.cs, different rectangle heights for are returned from GetNextRect and GetPropertyHeight (singleLineHeight+1 and singleLineHeight, respectively), which causes the Inspector to allocate 1 too few pixels for each entry in the Dictionary. For large numbers of entries, this ultimately causes those entries to be uneditable and unviewable via the inspector.

Proposed fix is to increase height of rectangle returned from GetPropertyHeight to singleLineHeight+1. In my opinion, a private padding variable is overkill.

```
        public override float GetPropertyHeight(SerializedProperty property, GUIContent label)
        {
            if(property.isExpanded)
            {
                var keysProp = property.FindPropertyRelative("_keys");
                return (keysProp.arraySize + 4) * (EditorGUIUtility.singleLineHeight + 1);
            }
            else
            {
                return EditorGUIUtility.singleLineHeight;
            }
        }
```

**Comment by lordofduct** [comment]
This version of Spacepuppy Framework is considered obsolete.

I have moved on to version 3.0:
https://github.com/lordofduct/spacepuppy-unity-framework-3.0

DictionaryPropertyDrawer and DrawableDictionary do not exist in this newer version (I never use it, but instead was created for a thread on unity forums). So I'm considering this not an issue to be resolved.

**Comment by Chazzz** [comment]
Ok, thanks for the update.
